export const GET_CHATS = "GET_CHATS";
export const GET_CHATS_FAILURE = "GET_CHATS_FAILURE";

export const SEND_NEW_MESSAGE_SUCCESS = "SEND_NEW_MESSAGE";
export const SEND_NEW_MESSAGE_FAILURE = "SEND_NEW_MESSAGE_FAILURE";

export const SEND_REPLY_SUCCESS = "SEND_REPLY_SUCCESS";
export const SEND_REPLY_FAILURE = "SEND_REPLY_FAILURE";

export const GET_SINGLE_CHAT_DETAILS = "GET_SINGLE_CHAT_DETAILS";

export const CLEAR_CONVERSATION = 'CLEAR_CONVERSATION';

